pipeline:

  format:
    image: hseeberger/scala-sbt:8u141-jdk_2.12.3_1.0.2
    commands: sbt scalafmtTest

  test:
    image: hseeberger/scala-sbt:8u141-jdk_2.12.3_1.0.2
    commands: sbt test

  slack:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
