pipeline:

  format:
    image: openjdk
    commands:
      - wget https://downloads.lightbend.com/scala/2.12.2/scala-2.12.2.deb
      - dpkg -i scala-2.12.2.deb
      - sbt scalafmtTest

  test:
    image: openjdk
    commands:
      - wget https://downloads.lightbend.com/scala/2.12.2/scala-2.12.2.deb
      - dpkg -i scala-2.12.2.deb
      - sbt test

  slack:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
